# Generated by Django 2.2.6 on 2019-10-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_auto_20191025_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_vi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
