# Generated by Django 2.2.6 on 2019-10-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_auto_20191025_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='phone_description_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_description_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_description_vi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
